name: Build kernel deb packages
on:
  watch:
    types: [started]

  workflow_dispatch:

  push:
    tags:
      - 'debian*'
jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: bash build_action.sh

      - name: Upload UEFI images
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images
          path: ./artifact/*.deb
          compression-level: 9
