name: Build kernel deb packages
on:
  watch:
    types: [started]

  workflow_dispatch:

  push:
    tags:
      - 'debian*'
jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: bash build_action.sh

      - uses: actions/checkout@v4
        with:
          name: linux-sm8250-aarch64-latest
          path: ${{ github.workspace }}/artifact/
  release:
    name: Publish release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: linux-sm8250-aarch64-latest

    - name: Upload assets
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.BUILD_TOKEN }}
        file: ./*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
